### ISSUE TITLE
Backup Droppy - Error Code: Source path does not exist

### ISSUE THREAD

**Issue by Big-Mac1975** [YunoHost-Apps/droppy_ynh#21]
hi, when i try to backup droppy with the backup function in yunohost there is a error code: Source path does not exist. And yunohost do not make a backup from droppy.

here is the log file:
https://paste.yunohost.org/raw/iyoxibogek

thx

**Comment by ericgaspar** [comment]
Can you check if the path `/home/yunohost.app/droppy` exits on your server?

**Comment by Big-Mac1975** [comment]
hi, yes it exists. there is a folder named "files" it is 4096 in size and the permissions are  "drwxr-xr-x"

thx

**Comment by Big-Mac1975** [comment]
Today I did an update to version (12.2.0~ynh10) and the problem still exists 
thx

**Comment by yalh76** [comment]
It's because `data_path` setting is not defined.
You should fix it from the command line : `yunohost app setting droppy data_path -v /home/yunohost.app/droppy`

**Comment by Big-Mac1975** [comment]
Thank you very much yalh76! Your answer was the solution!

**Comment by yalh76** [comment]
It was because in https://github.com/YunoHost-Apps/droppy_ynh/pull/17/files#diff-57aeb84da86cb7420dfedd8e49bc644fb799d5413d01927a0417bde753e8922f

`data_path` setting wasn't initialized during upgrade
