### ISSUE TITLE
Droppy is not maintained anymore

### ISSUE THREAD

**Issue by Tagadda** [YunoHost-Apps/droppy_ynh#25]
The upstream repository is archived.

https://github.com/silverwind/droppy/

**Comment by ericgaspar** [comment]
As stated in the disclaimer section in the README

**Comment by Tagadda** [comment]
It's flagged as High Quality App and shouldn't.
I think we should leave this open until the app is removed from the catalog.

**Comment by ericgaspar** [comment]
This app is functional and I don't agree to just remove it. I have close the issue because apart from deleting the repo there is little we can do to this repo. However, in the application catalog, we can add anti-features.
