### ISSUE TITLE
Not possible to create new files or folders in Droppy after restoring it from backup

### ISSUE THREAD

**Issue by rasmus-mk** [YunoHost-Apps/droppy_ynh#5]
**Describe the bug**
After restoring a backup of Droppy on a new system (instead of doing post-install), it wasn't possible to create new files or folders in the web interface. 
After some investigation it turned out that the Droppy data folder (/home/yunohost.app/droppy) had the wrong group and owner. Changing the group and owner to droppy:droppy fixes this problem.

**Versions**
- Hardware: *Raspberry Pi at home*
- YunoHost version: *4.0.4*
- I have access to my server: *Through SSH | Through the webadmin* 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: *yes*
  - If yes, please explain: Restoring my backup
- Current package version: *12.2.0~ynh1*

**To Reproduce**
- Install Droppy along with a lot of other apps.
- Create a backup containing droppy.
- Install Yunohost on a fresh system.
- Restore instead of post-install.

Just creating a backup and restoring it will probably not trigger this bug since the new droppy user/group that is created when the backup is restored will have the same uid/gid as the old user which is contained in the backup tar.gz it will thus get the correct owner:group.

**To Reproduce-2 (probably easier but not tested)**
I havn't tried this but the easiest way to reproduce is probably:
- Install droppy
- Backup droppy
- Install a random app
- Restore droppy.

The droppy data folder will now have the owner and group of the random app.

**Expected behavior**
It will not be possible to create new files or folders in the droppy web interface (but it will be possible to read the old ones). The droppy data dir when listed with ls -l will have some other owner and group than droppy:droppy (in my case it was freshrss:freshrss).

**Logs**
The does not show anything.

**Comment by ericgaspar** [comment]
Fixed with #6
